export const DEFAULT_LOCALE = 'en';

export const LOCALE_CHANGE_REQUEST = 'LOCALE_CHANGE_REQUEST';
export const LOCALE_CHANGE_SUCCESS = 'LOCALE_CHANGE_SUCCESS';
export const LOCALE_CHANGE_FAILURE = 'LOCALE_CHANGE_FAILURE';
